spring.application.name=skillmentor


spring.datasource.url=jdbc:postgresql://localhost:5432/skill_mentor_v2
spring.datasource.username=postgres
spring.datasource.password=1234@
spring.datasource.driver-class-name=org.postgresql.Driver

# JPA/Hibernate Configuration
spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true
spring.jpa.hibernate.ddl-auto=create-drop
